---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4
  customize:
    memory: 2048
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: mesosphere_master
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: mesosphere
        mesosphere:
          with_zookeeper: true
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6

  - name: mesosphere_slave
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: mesosphere
        slave:
          attributes:
            rackid: us-east-1b
          master: 'zk://localhost:2181/mesos'
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        # these keys below are only for master configurations.
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6
        mesosphere:
          with_zookeeper: true

  - name: source_master
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6

  - name: source_slave
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          ip: 127.0.0.1
          quorum: 1
        slave:
          master: 127.0.0.1:5050
        # these keys below are only for master configurations.
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        slave_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6
